### ISSUE TITLE
Greyed out tables when maxed level and maxed covenant

### ISSUE THREAD

**Issue by RogerRabbit10** [erglo/mission-report-button-plus#1]
Bro this addon is wack.

works with half my alts and not others, cant seem to actually recognise I have maxed the alt
maxed the cov
maxed it all

and its still telling me I'm not level 60....fix the coding thanks

**Comment by erglo** [comment]
Thank you for your feedback! It took me a while, but I think I found the problem. I reworked this feature and uploaded a fix. It should work now. Give it a new try. Enjoy!
