### ISSUE TITLE
Add packaging for non-Curse addon updaters

### ISSUE THREAD

**Issue by SpareSimian** [erglo/mission-report-button-plus#3]
Allow downloading the addon directly from GitHub via Wago or Ajour. It appears one can do that using this script:

https://github.com/BigWigsMods/packager

**Comment by erglo** [comment]
Thank you for pointing this out! I haven't used neither of them, yet, but I will definitely check them out. The more WoW addon websites/manager know about MRBP the better! 👍

**Comment by SpareSimian** [comment]
I used to use the Curse manager and then the Wolf one and Twitch. They're all quite slow, presumably because of the huge network load of displaying ads. Or because their contract requires that they delay a long time while displaying ads. I'm now using Ajour. It loads fast and it does the update step in the blink of an eye. I was amazed at how much time I was wasting with the other addon managers.

**Comment by erglo** [comment]
Done. It took a while to read into this topic, but this addon can now be downloaded from [CurseForge](https://www.curseforge.com/wow/addons/mission-report-button-plus), [WOWInterface](https://www.wowinterface.com/downloads/info26583-MissionReportButtonPlus.html), [Wago](https://addons.wago.io/addons/mission-report-button-plus), [GitHub](https://github.com/erglo/mission-report-button-plus) starting with current release ([v0.14.0](https://github.com/erglo/mission-report-button-plus/releases/tag/v0.14.0)).

**Comment by SpareSimian** [comment]
I just tested with Ajour and it works great. I used "Install from URL" and fed Ajour the URL for the GitHub project. The installation is almost instant.
